// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Grigorii Tropin
//
// tools-context — emit agent context file (TOOLS.md) from IPM graph.
// Calls idea status + idea show <name> → one-liner per working tool.

#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
#include <cjson/cJSON.h>

static int launch_command_capture_stdout_output(char *const argv[], char **out) {
    int pipefd[2];
    if (pipe(pipefd) < 0) return -1;
    pid_t pid = fork();
    if (pid < 0) { close(pipefd[0]); close(pipefd[1]); return -1; }
    if (pid == 0) {
        close(pipefd[0]);
        dup2(pipefd[1], STDOUT_FILENO);
        close(pipefd[1]);
        execvp(argv[0], argv);
        _exit(127);
    }
    close(pipefd[1]);

    size_t cap = 65536, len = 0;
    char *buf = malloc(cap);
    if (!buf) { close(pipefd[0]); return -1; }
    ssize_t n;
    while ((n = read(pipefd[0], buf + len, cap - len - 1)) > 0) {
        len += (size_t)n;
        if (len + 1 >= cap) {
            cap *= 2;
            char *t = realloc(buf, cap);
            if (!t) { free(buf); close(pipefd[0]); return -1; }
            buf = t;
        }
    }
    close(pipefd[0]);
    buf[len] = '\0';
    *out = buf;

    int ws;
    waitpid(pid, &ws, 0);
    return (WIFEXITED(ws) && WEXITSTATUS(ws) == 0) ? 0 : -1;
}

static cJSON *query_ipm_graph_json_format(const char *cmd, const char *arg) {
    char *argv[4] = { (char *)"idea", (char *)cmd, NULL, NULL };
    if (arg) argv[2] = (char *)arg;

    char *raw;
    if (launch_command_capture_stdout_output(argv, &raw) != 0) return NULL;

    cJSON *root = cJSON_Parse(raw);
    free(raw);
    return root;
}

int main(void) {
    cJSON *status = query_ipm_graph_json_format("status", NULL);
    if (!status) { fprintf(stderr, "tools-context: idea status failed\n"); return 1; }

    cJSON *packages = cJSON_GetObjectItemCaseSensitive(status, "packages");
    if (!cJSON_IsArray(packages)) {
        fprintf(stderr, "tools-context: no packages array\n");
        cJSON_Delete(status);
        return 1;
    }

    printf("# Vehir Tools — Agent Context\n\n");

    cJSON *pkg;
    cJSON_ArrayForEach(pkg, packages) {
        cJSON *name = cJSON_GetObjectItemCaseSensitive(pkg, "name");
        cJSON *proof = cJSON_GetObjectItemCaseSensitive(pkg, "proof_status");
        if (!cJSON_IsString(name) || !cJSON_IsString(proof)) continue;
        if (strcmp(proof->valuestring, "works") != 0) continue;

        cJSON *show = query_ipm_graph_json_format("show", name->valuestring);
        char *desc = NULL;
        if (show) {
            cJSON *obj = cJSON_GetObjectItemCaseSensitive(show, "package");
            if (obj) {
                cJSON *d = cJSON_GetObjectItemCaseSensitive(obj, "description");
                if (cJSON_IsString(d) && d->valuestring[0])
                    desc = strdup(d->valuestring);
            }
            cJSON_Delete(show);
        }
        printf("- **%s** — %s\n", name->valuestring, desc ? desc : "—");
        free(desc);
    }

    cJSON_Delete(status);
    printf("\n*Generated by tools-context from IPM graph.*\n");
    return 0;
}
