// Generated by spec2c from {{name}}.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <cjson/cJSON.h>
#include "vehir_lib.h"
{{db_includes}}

typedef struct vehir_db vehir_db;

extern int {{core_function}}(vehir_db *db, int argc, char **argv{{core_params_decl}});
